Exit installation if user cancels it when prompted for password
truenas/truenas-installer pull request #22
Opened 2020-09-21 20:01 UTC by sonicaj

2020-09-21 20:12 UTC, william-gr reviewed
Hmm why, in theory cancel password should work just fine. UI has menas to set it on first use.

2020-09-21 20:13 UTC, william-gr commented
My bad on the ticket, i didnt realize it at first.

2020-09-22 08:23 UTC, sonicaj commented
![Screenshot 2020-09-22 at 1 21 13 PM](https://user-images.githubusercontent.com/17968138/93859031-869f2900-fcd6-11ea-9368-f560c3712866.png)
@william-gr this is the updated dialog, please let me know if we would require changes to the layout.

2020-09-22 11:18 UTC, william-gr requested changes

2020-09-22 11:18 UTC, william-gr commented on usr/sbin/truenas-install
> +	    --extra-button --extra-label "Donot set password" \
Do not, missing space?

Or just Dont

2020-09-22 11:41 UTC, william-gr approved these changes

2020-09-22 11:41 UTC, merged