NAS-130002 / 24.10 / Replace TrueNAS with vendor in installer
truenas/truenas-installer pull request #87
Opened 2024-07-12 14:26 UTC by aiden3c

This replaces all written instances of TrueNAS with the vendor information, defaulting to TrueNAS if no vendor is supplied

2024-07-12 14:26 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130002

2024-07-12 14:28 UTC, themylogin commented on truenas_installer/installer.py
> +    def __init__(self, version, dmi, vendor=None):
Why the default value?

2024-07-12 14:29 UTC, themylogin commented on truenas_installer/installer.py
> +    def __init__(self, version, dmi, vendor=None):
This default value will never be used
```suggestion
    def __init__(self, version, dmi, vendor):
```

2024-07-12 14:32 UTC, aiden3c commented on truenas_installer/installer.py
> +    def __init__(self, version, dmi, vendor=None):
Good catch

2024-07-22 11:13 UTC, yocalebo requested changes

2024-07-22 11:13 UTC, yocalebo commented on truenas_installer/__main__.py
> +    try:
Let's be extra safe here. I'd rather just catch all exceptions and pass.

```
vendor = "TrueNAS"
try:
    with open(...
        vendor = ...
except Exception:
    pass

2024-07-22 13:40 UTC, yocalebo approved these changes
Thanks!

2024-07-22 13:45 UTC, merged

2024-07-22 13:46 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.